/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/Core/AppFooter.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('./src/components/Core/Index/DataTable.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DraftInvoiceModalFooter: typeof import('./src/components/Dialog/General/DraftInvoiceModalFooter.vue')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FinalInvoiceModalFooter: typeof import('./src/components/Dialog/General/FinalInvoiceModalFooter.vue')['default']
    Footer: typeof import('./src/components/Core/Footer.vue')['default']
    ForgotPasswordModal: typeof import('./src/components/Dialog/ForgotPasswordModal.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingModal: typeof import('./src/components/Dialog/General/LoadingModal.vue')['default']
    NavBar: typeof import('./src/components/Core/NavBar.vue')['default']
    NotFoundComponent: typeof import('./src/components/Core/NotFoundComponent.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    PreviewPDFModal: typeof import('./src/components/Dialog/General/PreviewPDFModal.vue')['default']
    PreviewPDFModal1: typeof import('./src/components/Dialog/General/PreviewPDFModal1.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ResultFinalInvoiceModal: typeof import('./src/components/Dialog/General/ResultFinalInvoiceModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectedBillsTableModal: typeof import('./src/components/Dialog/PerBatch/SelectedBillsTableModal.vue')['default']
    SelectedBillsTableModalFooter: typeof import('./src/components/Dialog/PerBatch/SelectedBillsTableModalFooter.vue')['default']
    SessionTimeoutModal: typeof import('./src/components/Dialog/General/SessionTimeoutModal.vue')['default']
    SummaryFinalInvoiceModalFooter: typeof import('./src/components/Dialog/General/SummaryFinalInvoiceModalFooter.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    FocusTrap: typeof import('primevue/focustrap')['default']
  }
}
